chore: updating yml file and simulator used in appium ios

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -67,6 +67,15 @@ workflows:
     steps:
     - activate-ssh-key@4: {}
     - git-clone@8: {}
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+
+
+            rm .node-version
     - yarn@0:
         inputs:
         - workdir: "$WORKDIR"
@@ -219,6 +228,15 @@ workflows:
     steps:
     - activate-ssh-key@4: {}
     - git-clone@8: {}
+    - script@1:
+        title: Remove .node-version
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+
+            rm .node-version
     - yarn@0:
         inputs:
         - workdir: "$WORKDIR"
@@ -257,6 +275,147 @@ workflows:
         title: Detox Test
         inputs:
         - command: detox:ios
+    - deploy-to-bitrise-io@2: {}
+  maestro-android:
+    description: |
+      Runs tests.
+
+      Next steps:
+      - Check out [Getting started with React Native apps](https://devcenter.bitrise.io/en/getting-started/getting-started-with-react-native-apps.html).
+    steps:
+    - activate-ssh-key@4: {}
+    - git-clone@8: {}
+    - avd-manager@1:
+        inputs:
+        - emulator_id: Pixel_4_API_31
+        - abi: x86_64
+        - api_level: '30'
+        title: Create emulator
+    - yarn@0:
+        inputs:
+        - workdir: "$WORKDIR"
+        - command: install
+        title: Install Dependencies
+    - script@1:
+        inputs:
+        - is_debug: 'yes'
+        - content: |-
+            #!/usr/bin/env bash
+
+            # fail if any commands fails
+            set -e
+
+            curl -Ls "https://get.maestro.mobile.dev" | bash
+        title: Add Maestro
+    - yarn@0:
+        title: Build app
+        inputs:
+        - command: android:release
+    - wait-for-android-emulator@1: {}
+    - script@1:
+        inputs:
+        - content: |
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # write your script here
+            export PATH="$PATH":"$HOME/.maestro/bin"
+            yarn maestro
+        title: Maestro test
+    - deploy-to-bitrise-io@2: {}
+    meta:
+      bitrise.io:
+        stack: linux-docker-android-20.04
+        machine_type_id: standard
+  maestro-ios:
+    description: |
+      Runs tests.
+
+      Next steps:
+      - Check out [Getting started with React Native apps](https://devcenter.bitrise.io/en/getting-started/getting-started-with-react-native-apps.html).
+    steps:
+    - activate-ssh-key@4: {}
+    - git-clone@8: {}
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+
+
+            rm .node-version
+    - yarn@0:
+        inputs:
+        - workdir: "$WORKDIR"
+        - command: install
+        title: Install Dependencies
+    - script@1:
+        title: Ruby gems & Pod install
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+
+            # install ruby gems
+            bundle install
+
+            # pod install
+            cd ios && bundle exec pod install
+    - script@1:
+        inputs:
+        - content: |-
+            #!/bin/bash
+
+            # applesimutils is a collection of utils for Apple simulators
+            brew tap wix/brew
+            brew install applesimutils
+
+            brew tap facebook/fb
+            brew install facebook/fb/idb-companion
+        title: Brew Dependencies
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+
+            curl -Ls "https://get.maestro.mobile.dev" | bash
+        title: Install maestro
+    - xcode-build-for-simulator@0:
+        inputs:
+        - configuration: Release
+        - simulator_device: iPhone 12
+        - output_dir: ios/build/Build/Products/Release-iphonesimulator
+    - xcode-start-simulator@0:
+        inputs:
+        - destination: platform=iOS Simulator,name=iPhone 12,OS=latest
+        - wait_for_boot_timeout: '90'
+    - script@1:
+        title: Install app
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+
+            DEVICE_ID=$(xcrun simctl list devices | grep "(Booted)" | grep -E -o -i "([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})")
+
+            xcrun simctl install $DEVICE_ID ./ios/build/Build/Products/Release-iphonesimulator/HelloApp.app
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+
+            export PATH="$PATH":"$HOME/.maestro/bin"
+
+            yarn maestro
+        title: Maestro test
     - deploy-to-bitrise-io@2: {}
 meta:
   bitrise.io:
